//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_2.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int ID { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public bool Admin { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tckno { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Ilce { get; set; }
        public string Il { get; set; }
        public int KargoID { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
