//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_2.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satislar()
        {
            this.SatisDetaylari = new HashSet<SatisDetaylari>();
        }
    
        public int SatisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public int KullaniciNo { get; set; }
        public decimal Tutar { get; set; }
        public int Miktar { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
        public byte TeslimDurumu { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisDetaylari> SatisDetaylari { get; set; }
    }
}
